apiVersion: v1
kind: Secret
metadata:
  name: metrika-secrets
  namespace: metrika
  labels:
    app: metrika
type: Opaque
stringData:
  GLPI_APP_TOKEN: "CHANGE_ME_BELGENET_APP_TOKEN"
  GLPI_USER_TOKEN: "CHANGE_ME_BELGENET_USER_TOKEN"
